import mongoose, { Document, Schema } from 'mongoose';

export interface ICelebration extends Document {
  tenantId: mongoose.Types.ObjectId;
  employeeId: mongoose.Types.ObjectId;
  type: 'birthday' | 'work_anniversary' | 'promotion' | 'new_hire' | 'retirement' | 'achievement' | 'other';
  title: string;
  date: Date;
  message?: string;
  isAutoGenerated: boolean;
  isPublic: boolean;
  wishes: { employeeId: mongoose.Types.ObjectId; message: string; at: Date }[];
  notificationSent: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const celebrationSchema = new Schema<ICelebration>(
  {
    tenantId: { type: Schema.Types.ObjectId, required: true, index: true },
    employeeId: { type: Schema.Types.ObjectId, required: true, ref: 'Employee' },
    type: { type: String, enum: ['birthday', 'work_anniversary', 'promotion', 'new_hire', 'retirement', 'achievement', 'other'], required: true },
    title: { type: String, required: true },
    date: { type: Date, required: true },
    message: String,
    isAutoGenerated: { type: Boolean, default: false },
    isPublic: { type: Boolean, default: true },
    wishes: [{ employeeId: Schema.Types.ObjectId, message: String, at: Date }],
    notificationSent: { type: Boolean, default: false },
  },
  { timestamps: true }
);

celebrationSchema.index({ tenantId: 1, date: 1 });
celebrationSchema.index({ tenantId: 1, employeeId: 1 });
export default mongoose.model<ICelebration>('Celebration', celebrationSchema);
