apiVersion: v1
kind: Namespace
metadata:
  name: hrm-production
  labels:
    app.kubernetes.io/name: hrm
    app.kubernetes.io/environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: hrm-staging
  labels:
    app.kubernetes.io/name: hrm
    app.kubernetes.io/environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: hrm-monitoring
  labels:
    app.kubernetes.io/name: hrm
    app.kubernetes.io/component: monitoring
